In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# @title Load dataset

data = pd.read_csv('5.csv')
print(data.head())

             eth_src            eth_dst  eth_type          ip_src  \
0  00:0c:29:92:2d:92  00:50:56:e7:f4:38      2048  192.168.17.128   
1  00:50:56:e7:f4:38  00:0c:29:92:2d:92      2048   162.159.200.1   
2  00:0c:29:92:2d:92  00:50:56:e7:f4:38      2054  192.168.17.128   
3  00:50:56:e7:f4:38  00:0c:29:92:2d:92      2054  192.168.17.128   
4  00:0c:29:92:2d:92  00:0c:29:87:03:2b      2048  192.168.17.128   

           ip_dst  ip_proto ip_flags_frag  src_port  dst_port  ip_ihl  \
0   162.159.200.1      17.0            DF   35880.0     123.0     5.0   
1  192.168.17.128      17.0           NaN     123.0   35880.0     5.0   
2   162.159.200.1      17.0            DF       NaN     123.0     5.0   
3             NaN       NaN           NaN       NaN       NaN     NaN   
4  192.168.17.130       1.0            DF       NaN       NaN     5.0   

   ip_chksum  ip_len  raw_load  packet_rate  payloads      label  
0    11851.0    76.0       NaN     0.598624         0     normal  
1    57090.0

In [ ]:
data.isnull().sum()

eth_src              0
eth_dst              0
eth_type             0
ip_src             248
ip_dst             254
ip_proto           734
ip_flags_frag    10716
src_port          3294
dst_port          3198
ip_ihl             734
ip_chksum          830
ip_len             734
raw_load          9456
packet_rate          0
payloads             0
label                0
dtype: int64

In [ ]:
# @title Replacing NULL values with 0
data['ip_src'].fillna("not available",inplace=True)
data['ip_dst'].fillna("not available",inplace=True)
data['ip_flags_frag'].fillna("not available",inplace=True)
data['src_port'].fillna(0,inplace=True)
data['dst_port'].fillna(0,inplace=True)
data['ip_ihl'].fillna(0,inplace=True)
data['ip_chksum'].fillna(0,inplace=True)
data['ip_len'].fillna(0,inplace=True)
data['raw_load'].fillna(0,inplace=True)
data['ip_proto'].fillna(0,inplace=True)
print(data)

                 eth_src            eth_dst  eth_type          ip_src  \
0      00:0c:29:92:2d:92  00:50:56:e7:f4:38      2048  192.168.17.128   
1      00:50:56:e7:f4:38  00:0c:29:92:2d:92      2048   162.159.200.1   
2      00:0c:29:92:2d:92  00:50:56:e7:f4:38      2054  192.168.17.128   
3      00:50:56:e7:f4:38  00:0c:29:92:2d:92      2054  192.168.17.128   
4      00:0c:29:92:2d:92  00:0c:29:87:03:2b      2048  192.168.17.128   
...                  ...                ...       ...             ...   
15771  00:0c:29:87:03:2b  00:50:56:e7:f4:38      2048  192.168.17.130   
15772  00:50:56:c0:00:08  ff:ff:ff:ff:ff:ff      2054  192.168.17.129   
15773  00:50:56:c0:00:08  ff:ff:ff:ff:ff:ff      2054  192.168.17.129   
15774  00:50:56:c0:00:08  ff:ff:ff:ff:ff:ff      2054  192.168.17.129   
15775  00:50:56:c0:00:08  ff:ff:ff:ff:ff:ff      2054  192.168.17.129   

               ip_dst  ip_proto  ip_flags_frag  src_port  dst_port  ip_ihl  \
0       162.159.200.1      17.0             D

In [ ]:
# @title Independent value (Pridictor variable)
X = data[['eth_src', 'eth_dst','eth_type', 'ip_src', 'ip_dst', 'ip_proto', 'ip_flags_frag', 'src_port', 'dst_port', 'ip_ihl', 'ip_chksum', 'ip_len', 'raw_load', 'packet_rate', 'payloads']].values
print(X)

[['00:0c:29:92:2d:92' '00:50:56:e7:f4:38' 2048 ... 0.0 0.598623722 0]
 ['00:50:56:e7:f4:38' '00:0c:29:92:2d:92' 2048 ... 0.0 102.5890986 0]
 ['00:0c:29:92:2d:92' '00:50:56:e7:f4:38' 2054 ... 0.0 0.598623722 0]
 ...
 ['00:50:56:c0:00:08' 'ff:ff:ff:ff:ff:ff' 2054 ... 0.0 7.164765955
  2133142]
 ['00:50:56:c0:00:08' 'ff:ff:ff:ff:ff:ff' 2054 ... 0.0 6.891975199
  2133142]
 ['00:50:56:c0:00:08' 'ff:ff:ff:ff:ff:ff' 2054 ... 0.0 6.480830401
  2133142]]


In [ ]:

y = data[['label']].values
print(y)

[['normal']
 ['normal']
 ['normal']
 ...
 ['normal']
 ['normal']
 ['normal']]


In [ ]:
# @title Encoding categorical data
from sklearn.preprocessing import LabelEncoder
LE_x = LabelEncoder()
X[:,0] = LE_x.fit_transform(X[:,0])
LE_x1 = LabelEncoder()
X[:,1] = LE_x1.fit_transform(X[:,1])
LE_x2 = LabelEncoder()
X[:,6] = LE_x2.fit_transform(X[:,6])
LE_x3 = LabelEncoder()
X[:,3] = LE_x3.fit_transform(X[:,3])
LE_x4 = LabelEncoder()
X[:,4] = LE_x4.fit_transform(X[:,4])

# Ensure y is a 1D array for the LabelEncoder
y = y.ravel()

LE_y = LabelEncoder()
y = LE_y.fit_transform(y)  # Apply the transformation to the entire y

# Handle potential NaNs introduced by LabelEncoder
import numpy as np
X = np.nan_to_num(X, nan=-1)  # Replace NaNs with a placeholder value (-1 in this case)

print(X)
print(y)

[[1 3 2048 ... 0.0 0.598623722 0]
 [3 1 2048 ... 0.0 102.5890986 0]
 [1 3 2054 ... 0.0 0.598623722 0]
 ...
 [2 13 2054 ... 0.0 7.164765955 2133142]
 [2 13 2054 ... 0.0 6.891975199 2133142]
 [2 13 2054 ... 0.0 6.480830401 2133142]]
[1 1 1 ... 1 1 1]


In [ ]:
# @title Train all data
from sklearn.model_selection import train_test_split
# No need to convert to dense, X is already a NumPy array
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 1)
print(X_train)
print(y_train)

[[3 0 2048 ... 222.0 23.09812257 1836890]
 [0 3 2048 ... 40.0 3.266911565 10984]
 [0 3 2048 ... 0.0 36.76556594 429470]
 ...
 [0 3 2048 ... 378.0 9.706797283 1832669]
 [3 0 2048 ... 0.0 120.2096667 29389]
 [2 13 2054 ... 0.0 19.24683604 1955097]]
[1 1 1 ... 1 1 1]


In [ ]:
# @title Test all data
print(X_test)
print(y_test)

[[0 3 2048 ... 175.0 20.69911754 261261]
 [1 0 2048 ... 0.0 3.028444134 1619070]
 [3 0 2048 ... 0.0 15.37484558 1875485]
 ...
 [3 0 2048 ... 685.0 107.8960332 45074]
 [0 1 2048 ... 40.0 7.820070716 1896825]
 [3 1 2048 ... 27.0 23.90317238 1596842]]
[1 0 1 ... 1 1 1]


In [ ]:
# @title Train Model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# @title Predictions
from sklearn.metrics import roc_curve, roc_auc_score
pred_y = model.predict(X_test)
auc = roc_auc_score(y_test,pred_y)
fpr, tpr, thresholds = roc_curve(y_test, pred_y)

print(fpr)
print(tpr)
print(thresholds)
print(auc)

[0.         0.37476099 1.        ]
[0.         0.93923281 1.        ]
[2 1 0]
0.7822359100082131


In [ ]:
# @title Evaluate Model
from sklearn.metrics import accuracy_score, precision_score, recall_score
acc = accuracy_score(y_test,pred_y)
ps = precision_score(y_test,pred_y)
rs = recall_score(y_test,pred_y)
auc = roc_auc_score(y_test, pred_y)
print("Accuracy Score : ",acc)
print("Precision Score : ",ps)
print("Recall Score : ",rs)
print("AUC : ",auc)


Accuracy Score :  0.8871989860583016
Precision Score :  0.9265642562757587
Recall Score :  0.9392328142802886
AUC :  0.7822359100082131


In [ ]:
import pickle
# Save model to a file
with open('ids_model.pkl', 'wb') as file:
    pickle.dump(model, file)
